### ISSUE TITLE
Commit Log

### ISSUE THREAD

**Issue by corneezius** [abenoit79/jamming3#1]
I appreciate all your hard work on this project! It's important though that you make detailed commits as you work. When you get to larger projects, this will help you and collaborators more easily target areas in your code that need improvement. As a point of practice, try completing this sentence when making commits: "This commit will....." and that part should be the commit message.

Try to commit as you add in new features or sections of app.Making detailed commits might seem trivial to some developers, but when working with a team or collaborators, maintaining a detailed commit log is essential.

**Comment by abenoit79** [comment]
Okay, good to know.  I have never coded with groups before, so I am new to the whole Github thing.
