### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by corneezius** [abenoit79/jamming3#4]
Meets expectations

Awesome work with this project! Every feature seems to be working fine. If you really want to spice things up, I'd encourage you to see if you dig even deeper to the project by adding implementing one of the feature requests. Would also be good to spend a couple more hours trying to make the design flashier, as a lot of these projects are out there styled in this manner. Keep up good work!

**Comment by abenoit79** [comment]
Thank you, I will work on that.
